### ISSUE TITLE
(Continue) opnieuw -> doorgaan

### ISSUE THREAD

**Issue by NickMous** [tintin10q/pythonl#10]
Ik zou bij continue iets van doorgaan of verder gebruiken, want zodra je dit in een terwijl/zolang of voor herhaling gebruikt, hoeft het niet te betekenen dat je de herhaling opnieuw start. Leuk project overigens, zou het misschien best eens gebruiken voor scripts :)

**Comment by tintin10q** [comment]
Bedankt! En goed punt, ik heb dit sleutel woord in mijn hoofd altijd een beetje als opnieuw gezien omdat als ik wil stoppen met de loop dat ik dan `stop` gebruik. Dit is de eerste keer dat ik hier zo over nadenk. Maar klopt helemaal. Daarnaast is het ook een meer 1 op 1 vertaling.

**Comment by tintin10q** [comment]
Wat vind je van door? Ietje korter en ik denk dat het wel hetzelfde leest @NickMous.

**Comment by tintin10q** [comment]
Nee verder is beter dan door denk ik

**Comment by tintin10q** [comment]
`vervolg` is ook nog een optie.

**Comment by NickMous** [comment]
Dan zou ik kiezen uit door/doorgaan/vervolgen, of dat je ze alle 3 beschikbaar maakt? Doorgaan is wel de letterlijke vertaling denk ik, anders kan ik even in een woordenboek kijken, van dale, ipv translate lol

**Comment by tintin10q** [comment]
Ok ik ben voor doorgaan gegaan. Bedankt!
