### ISSUE TITLE
We zijn async en await vergeten

### ISSUE THREAD

**Issue by tintin10q** [tintin10q/pythonl#2]
Wat is misschien een goed alternatief voor async en await?

async kan denk ik wel gewoon blijven zoals die is. Het woord asynchroon begint ook met async. 

Maar dan hebben we nog `await`. Ik denk dat het wel goed is om 1 woord te doen en niet iets met een spatie. 

Misschien `wacht` of `wachtop`?

Vedere suggesties zijn welkom.

**Comment by Stef-Gijsberts** [comment]
Ik vind `wacht` mooi als vertaling voor `await`. Of `verwacht`.

`async` is inderdaad al wel duidelijk. Een langere, Nederlandsere variant zou `ongelijktijdig` zijn. Of wellicht een afkorting daarvan.

Of misschien `asynch`? Dat vind ik ook wel leuk.

**Comment by tintin10q** [comment]
Ik denk dat `async` en `wacht` het beste zijn.

**Comment by tintin10q** [comment]
Het is toch `async` en `wachtop` geworden.
