### ISSUE TITLE
match en case

### ISSUE THREAD

**Issue by tintin10q** [tintin10q/pythonl#3]
match kan natuurlijk gewoon match blijven en ik dacht `optie` voor case.

Maar deze zijn wat moeilijker want dat zijn alleen sleutel woorden als je de juiste syntax van match gebruikt.

**Comment by Stef-Gijsberts** [comment]
Ik vind Marijns vertalingen `vergelijk` en `geval` hiervoor mooi.

**Comment by tintin10q** [comment]
Goed idee!

**Comment by tintin10q** [comment]
Dit bestaat nu
