### ISSUE TITLE
De __name__ variable

### ISSUE THREAD

**Issue by tintin10q** [tintin10q/pythonl#6]
Ik doe hier een voorstel. 

Je ziet vaak deze code:

```pythonl
indien __name__ == '__main__':
    print("hoi")
```

We zouden een transformatie van  `__naam__` naar `__name__` kunnen doen. Dan krijg je dus: 

```pythonl
indien __naam__ == '__main__':
    print("hoi")
```

Ik denk niet dat we de `__main__` moeten/kunnen aanpassen.

Dan krijg je ook leuke dingen dingen als

```
def hoi():
    niet

print(hoi.__naam__)    
```

Gewoon werken. 

Maar kan dit met de tokenizer? Want je zou het eigenlijk zo willen dat het niet aangepast word in een string. Iets als:

```pythonl
hoi = "hoi __naam__ daar"
```

**Comment by tintin10q** [comment]
Misschien moeten we het maar bij sleutel woorden houden

**Comment by Stef-Gijsberts** [comment]
Dat moet wel kunnen, maar het zou wel problemen kunnen veroorzaken qua compatibiliteit met bestaande python. Want dit zou geen syntaxwijziging zijn, maar echt een semantische wijziging.

**Comment by tintin10q** [comment]
Ja precies laten we het maar niet doen
